### ISSUE TITLE
Deleting all (finished ) tasks at once

### ISSUE THREAD

**Issue by 0xmycf** [hood/rudo#1]
Hello, neat little tool. I am looking forward to using it. 

But I think there is no option to delete all finished tasks at once, which would be a useful feature. (I see myself setting up a cronjob to clear them out for example)

Maybe something like
`rudo --delete-all`
`rudo --delete-all-finished`

**Comment by hood** [comment]
Thank you for your interest. Feature in latest commit ([e448942](https://github.com/hood/rudo/commit/e448942b752c56dd2be2e2bb5026ced45e215ed6))!

**Comment by 0xmycf** [comment]
Hey, I saw that you added a comment saying that you don't know how to use filter there. I am also still learning rust, so idk if my solution is how one should do it.

```rs
       self.list = self.list.iter()
            .filter(|item| !item.completed)
            .map(TodoItem::clone)
            .collect();
```

But this required adding the `Clone` trait to `TodoItem`. But as I said, I don't know if it's idiomatic to clone in that situation.
